version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - "db.env"
    ports:
      - "5432:5432"
  goscrapper:
    build: ./
    command: ./goscrapper
    ports:
      - "8089:8089"
    env_file:
      - "db.env"
    depends_on:
      - postgres
